In [ ]:
import pandas as pd

from datetime import datetime
import os
import json
from openpyxl.styles import PatternFill
import pandas as pd
import re

In [9]:
import pandas as pd
import re

def sanitize_df_column_names(df: pd.DataFrame) -> pd.DataFrame:
    """
    Sanitize DataFrame column names by:
    - Stripping leading/trailing whitespace
    - Replacing multiple internal spaces with a single space

    Args:
        df (pd.DataFrame): Input DataFrame

    Returns:
        pd.DataFrame: A new DataFrame with cleaned column names
    """
    # Create a copy to avoid mutating the original DataFrame
    cleaned_df = df.copy()

    cleaned_df.columns = [
        re.sub(r"\s+", " ", col).strip()
        for col in cleaned_df.columns
    ]

    return cleaned_df

In [17]:

def mastersheet_data_load(file_path):

       # read the excel file and see the sheet names
       xl_files = pd.ExcelFile(file_path)

       target_sheets = "Master"
       
       if target_sheets in xl_files.sheet_names:
              hyundai_master_sheet_df = pd.read_excel(file_path, sheet_name=target_sheets, skiprows=1)

       # Keeping only the columns we need

       key_columns_to_keep = ['Model Year From', 'Model', 'Trim 1', 'Trim 2',
              'Trim 3', 'Trim 4', 'Trim 5', 'Trim 6', 'Trim 7', 'Trim 8',
              'Accessory Description', 'Accessory Description (FR)',
              'Part Number', 'DNET', 'MSRP', 'Labour Rate', 'Suggested Labour Hours',
              'Suggested Base Retail Price w labour', 'Comments', 'Comments (FR)']

       # sanitize column names

       clean_df = sanitize_df_column_names(hyundai_master_sheet_df)

       hyundai_master_sheet_df = clean_df[key_columns_to_keep]


       hyundai_master_sheet_df = hyundai_master_sheet_df.dropna(axis=1, how='all')

       # changed column names for master_file

       column_names_to_change = {
       'Model Year From': "Year", 
       'PartNumber':'PartNumber', 
       'Suggested Labour Hours':'Labour Hours',
       'Suggested Base Retail Price w labour':'MSPR w/labour'}

       hyundai_master_sheet_df.rename(columns=column_names_to_change, inplace=True)

       return hyundai_master_sheet_df 


FilePath = r"..\landing_zone\2026\Hyundia\may-2026\2026-5-1 HACC MAF DIST - 05122026.xlsx"
hyundai_master_sheet_df = mastersheet_data_load(FilePath)

c:\Users\paxm\AppData\Local\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Data Validation extension is not supported and will be removed
  for idx, row in parser.parse():

In [19]:
hyundai_master_sheet_df.columns

Index(['Year', 'Model', 'Trim 1', 'Trim 2', 'Trim 3', 'Trim 4', 'Trim 5',
       'Trim 6', 'Trim 7', 'Accessory Description',
       'Accessory Description (FR)', 'Part Number', 'DNET', 'MSRP',
       'Labour Rate', 'Labour Hours', 'MSPR w/labour', 'Comments',
       'Comments (FR)'],
      dtype='object')

In [4]:
hyundai_master_sheet_df.head()

,Year,Model,Trim 1,Trim 2,Trim 3,Trim 4,Trim 5,Trim 6,Trim 7,Accessory Description (EN),Accessory Description (FR),PartNumber,DNET,MSRP,Labour Rate,Labour Hours,MSPR w/labour,Comments (EN),Comments (FR)
0,2024,Palisade,Pref,Urban,Calli,NaN,NaN,NaN,NaN,Premium Folding Cargo Tray,Plateau de chargement pliable premium,S8H12AP000,207.11,302.70,136.95,0.0,302.700,NaN,NaN
1,2024,Palisade,Pref,Urban,Calli,NaN,NaN,NaN,NaN,Rubber Cargo Tray Behind 3rd Row,Plateau de chargement 3e rangée,S8H12AP200,90.13,125.14,136.95,0.0,125.140,NaN,NaN
2,2024,Palisade,Pref,Urban,Calli,NaN,NaN,NaN,NaN,Cargo Net - Envelope Style,Filet de coffre enveloppant,AMCARGONET,27.97,43.35,136.95,0.1,57.045,Installation required,Installation requise
3,2024,Palisade,Pref,Urban,Calli,NaN,NaN,NaN,NaN,Cargo Shelf,Etagere de chargement,000AM18425,261.68,401.14,136.95,0.1,414.835,NaN,NaN
4,2024,Palisade,Pref,Urban,Calli,NaN,NaN,NaN,NaN,Trunk Lip Protector,Protège-rebord de coffre,000AM00841,51.73,79.59,136.95,0.0,79.590,NaN,NaN

In [20]:
# set standard column names for master file
standard_column_names = ['Year', 'Model', 'Trim', 'Description', 'Part',
       'DNET', 'MSRP', 'Labour Rate', 'Hours', 'MSPR w/labour',
       'Comments']

In [21]:
def hyundai_model_load():
       # load Hyundia model db

       hyundai_model_db_df = pd.read_csv(r"..\database\dbs\Hyundai_models_db.csv")

       # very special changes 

       # mask = (hyundai_model_db_df["Year"] == 2024) & (hyundai_model_db_df["Model"].str.lower() == "elantra") & (hyundai_model_db_df["Trim"].str.contains(r"\bHybrid Luxury\b", case=False))


       # # Replace "Hybrid Luxury" with "HEV" in Trim for those records
       # hyundai_model_db_df.loc[mask, "Trim"] = hyundai_model_db_df.loc[mask, "Trim"].str.replace(r"\bHybrid Luxury\b", "HEV", case=False, regex=True)

       return hyundai_model_db_df

hyundai_model_db_df = hyundai_model_load()

In [22]:

# def transform_vehicle_data(df):
#     """
#     Transforms vehicle data by applying trim corrections and model/year-specific changes.
    
#     Args:
#         df (pd.DataFrame): DataFrame with columns ['Year', 'Model', 'Trim'].
    
#     Returns:
#         pd.DataFrame: Transformed DataFrame.
#     """
    
#     # General trim corrections
#     data_to_change_on_trim = {
#         "Caligraphy": "Calligraphy",
#         # "Calli ICE": "Calligraphy",
#     }
    
#     # Model/year-specific changes
#     change_for_specific_veh = {
#         "Tucson": {
#             2026: {"Ultimate AWD": "Utlimate PHEV"}
#         },
#         "Kona": {
#             2026: {"Pref w/Ult Pkg": "Preferred w/Ultimate Pkg"}
#         }
#     }
    
#     # Santa Fe-specific changes
#     changes_for_santafe = {
#         "Preferred Hybrid": "Preferred HEV",
#         "Luxury Hybrid": "Luxury HEV",
#         "Calligraphy Hybrid": "Calligraphy HEV"
#     }
    
#     # 1. Apply general trim corrections
#     df["Trim"] = df["Trim"].replace(data_to_change_on_trim)
    
#     # 2. Apply model/year-specific changes
#     for model, year_dict in change_for_specific_veh.items():
#         for year, trim_changes in year_dict.items():
#             for old_trim, new_trim in trim_changes.items():
#                 mask = (df["Model"] == model) & (df["Year"] == year) & (df["Trim"] == old_trim)
#                 df.loc[mask, "Trim"] = new_trim
    
#     # 3. Apply Santa Fe-specific changes
#     for old_trim, new_trim in changes_for_santafe.items():
#         mask = (df["Model"] == "Santa Fe") & (df["Trim"] == old_trim)
#         df.loc[mask, "Trim"] = new_trim
    
#     return df

In [23]:


print(os.path.exists(r'..\database\keywords_db\tokenized_key_words.json'))

with open(r'..\database\keywords_db\tokenized_key_words.json', 'r') as file:
    tagy = json.load(file)
    tagy = (lambda obj: {k.lower(): (v.lower() if isinstance(v, str) else v) for k, v in obj.items()})(tagy)

True

In [24]:
missing_model_num_ = pd.DataFrame(columns=["Year", "Model", "Trim"])
missing_keyword = {}

In [25]:
def find_trim_columns_in_df(df):
    trim_columns = [col for col in df.columns if "trim" in col.lower()]
    return trim_columns


# helper function to show unique values in the master file

def show_unique_values(df, columns):
    """
    Display unique values for the specified columns in a DataFrame.
    
    Parameters:
    df (pd.DataFrame): The DataFrame to analyze.
    columns (list): List of column names to check.
    
    Returns:
    dict: A dictionary with column names as keys and unique values as lists.
    """
    unique_dict = {}
    for col in columns:
        if col in df.columns:
            unique_dict[col] = df[col].unique().tolist()
            # print(f"{col}: {df[col].unique().tolist()}")
        else:
            unique_dict[col] = "Column not found"
    return unique_dict



def filter_tags(tag_dict, to_remove):
    """
    Removes unwanted values from the 'tags' lists in a dictionary.

    Parameters:
        tag_dict (dict): Dictionary where each key has a 'tags' list.
        to_remove (set): Set of values to remove from the tags.

    Returns:
        dict: A new dictionary with filtered tags.
    """
    filtered_dict = {}

    for key, value in tag_dict.items():
        if "tags" in value and isinstance(value["tags"], list):
            # Keep only tags not in to_remove
            new_tags = [tag for tag in value["tags"] if tag not in to_remove]
            filtered_dict[key] = {"tags": new_tags}

    return filtered_dict



def create_keyword_dictionary(input_set):
    """
    Takes a set of strings, splits each string by spaces,
    and returns a set of unique keywords.
    
    Parameters:
        input_set (set): A set containing strings.
    
    Returns:
        set: A set of unique keywords.
    """
    keyword_dictionary_set = set()
    
    for value in input_set:
        if isinstance(value, str):  # Ensure it's a string
            words = value.split()   # Split by spaces
            keyword_dictionary_set.update(words)  # Add words to the set
    
    return keyword_dictionary_set


def find_uniq_trimNames_in_df(df):
    uniq_trim_list = set()
    trim_columns_list = find_trim_columns_in_df(df)
    for item in trim_columns_list:
        uniq_trim_list.update(df[item].dropna().unique())
    return uniq_trim_list

def is_tag_available(search_kwd):
    if search_kwd not in tagy.keys():
        return "Unavailable"
    
    return tagy[search_kwd]["tags"]

In [26]:
unique_trim_list = find_uniq_trimNames_in_df(hyundai_master_sheet_df)

In [27]:
def get_model_numbers(year, model, trim, tags_list):

    pattern = ''.join(f'(?=.*{kw})' for kw in tags_list)  # constructing search keywords pattern 

    
    res_df = hyundai_model_db_df[
        (1==1)
        &(hyundai_model_db_df["Year"] == year) 
        & (hyundai_model_db_df["Model"].str.lower() == model.lower()) 
        & (hyundai_model_db_df["Tags"].str.contains(pattern, case=False, na=False))
    ]

    if len(res_df) <= 0:
        return {"status": 400,
                "value":"",
                    "msg": "No Model number record found. get_model_num_by_YM_wt..()"}
    
    response = {"status": 200, 
                "value": res_df['ModelNumber'].to_list(),
                "msg": "Found model number. get_model_num_by_YM_wt..()"}
    

    return response 

# def get_model_number_by_year_model_with_trim_key_word(year, model, kwd):
    
#     pattern = ''.join(f'(?=.*{kw})' for kw in kwd)  # constructing search keywords pattern 
#     # print(pattern)


#     res_df = hyundai_model_db_df[
#         (1==1)
#         &(hyundai_model_db_df["Year"] == year) 

#         & (hyundai_model_db_df["Model"].str.lower() == model.lower()) 
#         & (hyundai_model_db_df["Trim"].str.contains(pattern, case=False, na=False))
#     ]

    
#     if len(res_df) <= 0:
#         return {"status": 400,
#                 "value":"",
#                     "msg": "No Model number record found. get_model_num_by_YM_wt..()"}
    
#     response = {"status": 200, 
#                 "value": res_df,
#                 "msg": "Found model number. get_model_num_by_YM_wt..()"}
#     return response 


# def get_tags_by_model_and_trim(trim):
#     # return tag_keywords[trim]
#     tag_search_results = tagy[trim]["tags"]

#     if len(tag_search_results) <=0:
#         missing_keyword[trim] = 'Missing kwd'
#         return tag_search_results
    
    
#     return {"status": 200,
#                     "value": tag_search_results,
#                      "msg": "Found tag to use for modelNumber search. get_tag..()"}

def tockenize_trim(trim):

    trim = trim.strip().lower()
    search_tags = trim.split()

    return search_tags

def get_tags_by_trim(trimName, tagy):
    
    tags_list = tockenize_trim(trimName)
    tag_list_to_search =[]

    
    for tag in tags_list:
        if tag in tagy:
            tag_list_to_search.append(tagy[tag])

    if len(tag_list_to_search) <= 0:
        response = {
            "status": 400,
            "value": tag_list_to_search,
            "msg": "No tags found. get_model_num_by_YM_wt..()"
        }
    else:
        response = {
            "status": 200,
            "value": tag_list_to_search,
            "msg": "Found model number. get_model_num_by_YM_wt..()"
        }

    return response


def fetch_model_numbers(year, model, trim):
    
    search_response = get_tags_by_trim(trim, tagy)


    if search_response["status"] == 400:
        return search_response
    
    tags = search_response["value"]
    get_model_nums_search_response = get_model_numbers(year, model, trim, tags)
    
    # print(get_model_nums_search_response)

    if (get_model_nums_search_response["status"]==400):
        missing_model_num_.loc[len(missing_model_num_)] = [year, model, trim]

        return get_model_nums_search_response
    model_nums = get_model_nums_search_response["value"]

    return {
            "status": 200,
            "value": model_nums,
            "msg": "Found modelNumbers. search_hyundai_db_by_model_year_trim()"}

In [28]:
# fetch_model_numbers(2026, "Palisade", "Calli ICE")

In [29]:
# pattern = ''.join(f'(?=.*{kw})' for kw in ['cali', 'ice'])

# hyundai_model_db_df[
#         (1==1)
#         &(hyundai_model_db_df["Year"] == 2026) 
#         & (hyundai_model_db_df["Model"].str.lower() == 'Palisade') 
#         # & (hyundai_model_db_df["Tags"].str.contains("nhl", case=False, na=False))
#         # & (hyundai_model_db_df["Tags"].str.contains(pattern, case=False, na=False))
#     ]

In [30]:
# hyundai_master_sheet_df.columns

In [31]:
# hyundai_master_sheet_df[
#     (1==1)
#     & (hyundai_master_sheet_df["Model"]=="Palisade")
#     & (hyundai_master_sheet_df["Trim 3"]=="Calli")
#     & (hyundai_master_sheet_df["Accessory Description (EN)"].str.contains ("Mud Guard Kit"))
    
#     #    & (hyundai_master_sheet_df["Year"]=="2026")
#                         ]

In [32]:
hyundai_master_sheet_df.head()

,Year,Model,Trim 1,Trim 2,Trim 3,Trim 4,Trim 5,Trim 6,Trim 7,Accessory Description,Accessory Description (FR),Part Number,DNET,MSRP,Labour Rate,Labour Hours,MSPR w/labour,Comments,Comments (FR)
0,2024,Palisade,Pref,Urban,Calli,NaN,NaN,NaN,NaN,Premium Folding Cargo Tray,Plateau de chargement pliable premium,S8H12AP000,207.11,302.70,136.95,0.0,302.700,NaN,NaN
1,2024,Palisade,Pref,Urban,Calli,NaN,NaN,NaN,NaN,Rubber Cargo Tray Behind 3rd Row,Plateau de chargement 3e rangée,S8H12AP200,90.13,125.14,136.95,0.0,125.140,NaN,NaN
2,2024,Palisade,Pref,Urban,Calli,NaN,NaN,NaN,NaN,Cargo Net - Envelope Style,Filet de coffre enveloppant,AMCARGONET,27.97,43.35,136.95,0.1,57.045,Installation required,Installation requise
3,2024,Palisade,Pref,Urban,Calli,NaN,NaN,NaN,NaN,Cargo Shelf,Etagere de chargement,000AM18425,261.68,401.14,136.95,0.1,414.835,NaN,NaN
4,2024,Palisade,Pref,Urban,Calli,NaN,NaN,NaN,NaN,Trunk Lip Protector,Protège-rebord de coffre,000AM00841,51.73,79.59,136.95,0.0,79.590,NaN,NaN

In [33]:
def data_extract_all(missing_model_num_):
    dataset_summary = pd.DataFrame(columns=['Year', 'Model', 'Trim', 'Record_Count'])
    year_model_trim_dict = {}
    missing_model_num_ = missing_model_num_.loc[0:0]
    # missing_keyword = {}

    # Looping through the master file by year/model and trim

    for year in hyundai_master_sheet_df['Year'].unique():
        for model in hyundai_master_sheet_df['Model'].unique():

    # filtering to the current iteration for year and Model        
            model_df = hyundai_master_sheet_df[
                (hyundai_master_sheet_df['Year'] == year) &
                (hyundai_master_sheet_df['Model'] == model)
            ]
            # source_file = hyundai_master_sheet_df[]
    # Getting only the name of Trim columns in the vehicle DF
            filtered_columns = [col for col in model_df.columns if "trim" in col.lower()]

    # Looping through unique model df, capturing          
            for col in filtered_columns:
                trims = model_df[col].dropna().unique().tolist()
                # skip empty trim columns
                if len(trims) == 0:
                    continue            
                
                trim_name = trims[0]  # grab the trim name in that column. Colum has only one trim name at this point. 
                
                # We are going to create a file for each trim name 
                # Filter the list searching by trimName and save the list 
                if trim_name:
                    
                    # filter by trim name and save a new list
                    subset_df = model_df[model_df[col] == trim_name]
                    
                    # grab all the colms in the subset with the keyword trim
                    copy_filtered_columns = [c for c in subset_df.columns if "trim" in c.lower()]  # grab all trim columns in the subset
                    
                    copy_filtered_columns.remove(col)  # drop the current trim column that we want to keep

                    subset_df = subset_df.drop(columns=copy_filtered_columns)  #  drop all trim columns except the one we want to keep
                    subset_df.rename(columns={col: 'Trim'}, inplace=True)       # rename the current trim column to 'Trim' for clarity
                    
                    # create copy of the subset dataframe and store both in the dist as english and french versions
                    # Identify columns containing "(EN)"
                    English_columns = [col for col in hyundai_master_sheet_df.columns if "(EN)" in col]
                    French_columns = [col for col in hyundai_master_sheet_df.columns if "(FR)" in col]

                    # Initialize nested dict if not exists
                    key = (year, model, trim_name)
                    year_model_trim_dict.setdefault(key, {"EN":pd.DataFrame(), "FR":pd.DataFrame()})

                    # Remove English columns for French version and vice versa
                    # first check if there are any columns to drop

                    # get model numbers by year/model/trim
                    # they could be one or many, just because
                    # some trims come w/t different options
                    # and some have different version that came at different times of the year same trims
                    
                    # Created a list that will get all the model_numbers, they each will have a copy of the data for the particular trim, since they are all handled as unique vehicles.
                    modelNum_search_results = fetch_model_numbers(year = year, model=model, trim = trim_name)


                    if modelNum_search_results["status"] == 200:

                        model_nums = modelNum_search_results["value"]

                        # loop through all model numbers and create a copy list for each model number
                        for modelnum in model_nums:
                            
                            if len(French_columns) > 0:
                                uniq_model_accy_list = subset_df.drop(columns=French_columns)

                                # standardize column names for French version
                                uniq_model_accy_list.columns = standard_column_names
                                
                                # get the model_number of the vehicle and add it to the dataframe
                                
                                uniq_model_accy_list["ModelNumber"] = modelnum

                                year_model_trim_dict[key]["EN"] = pd.concat([year_model_trim_dict[key]["EN"], uniq_model_accy_list], ignore_index=True)
                                

                            if len(English_columns) > 0:
                                
                                uniq_model_accy_list = subset_df.drop(columns=English_columns)

                                # standardize column names for French version
                                uniq_model_accy_list.columns = standard_column_names
                                
                                # get the model_number of the vehicle and add it to the dataframe
                                
                                uniq_model_accy_list["ModelNumber"] = modelnum
                                # year_model_trim_dict[key]["FR"].columns = 
                                year_model_trim_dict[key]["FR"] = pd.concat([year_model_trim_dict[key]["FR"], uniq_model_accy_list], ignore_index=True)
                                
                                # then drop some columns to match rate importer format
                                # then group all the df for each model and year and finally save them to an excel files
                
                            
                            
                
                            # dataset_summary[(year, model, trim_name)] = len(subset_df)
                            dataset_summary.loc[len(dataset_summary)] = [year, model, trim_name, len(subset_df)]
                            
    return year_model_trim_dict, dataset_summary

In [ ]:
def merge_lists_by_model_number(master_dict):
    merged_dict = {}

    # Merge all DataFrames by model and language
    for (year, model, trim_name), value in master_dict.items():
        if model not in merged_dict:
            merged_dict[model] = {}

        for lang, accy_list in value.items():
            if lang not in merged_dict[model]:
                merged_dict[model][lang] = pd.DataFrame()

            merged_dict[model][lang] = pd.concat([merged_dict[model][lang], accy_list], ignore_index=True)

    # Filter and rename columns after merging
    required_columns = ["Year", "ModelNumber", "Description", "Part", "MSRP", "Hours", "Comments"]

    for model, lang_dict in merged_dict.items():
        for lang, df in lang_dict.items():
            if not df.empty:
                
                # display(df.head(3))
                existing_cols = [col for col in required_columns if col in df.columns]
                filtered_copy = df[existing_cols].copy()

                # Mapping old column names to new column names for renaming
                # rename_map = {old: new for old, new in zip(required_columns, rate_importer_column_names) if old in existing_cols}

                # added line for visibility of the mapping for the output file column names to match the rate importer format. This is important since we are removing some columns and renaming some columns to match the rate importer format, so this mapping will help us to keep track of the changes we are making to the master file columns to match the rate importer format.

                rename_map = {
                    "ModelNumber": "Model",
                    "MSRP": "Price",
                    "Labour Hours": "Hours"
                }
                
                # renaming the columns to match the rate importer format
                filtered_copy.rename(columns=rename_map, inplace=True)
                
                # saving the filtered and renamed copy back to the merged dict
                if "Part" not in filtered_copy.columns or "Price" not in filtered_copy.columns:
                    raise ValueError(f"'Part' or 'Price' column is missing in the DataFrame for model {model} and language {lang}. Available columns: {filtered_copy.columns.tolist()}")
                
                

                merged_dict[model][lang] = filtered_copy
                
    return merged_dict

In [35]:
def get_upload_report(merged_files_dict):
    for keys, values in merged_files_dict.items():
        en_cols = len(values["EN"].columns) if "EN" in values and isinstance(values["EN"], pd.DataFrame) else "NA"
        fr_cols = len(values["FR"].columns) if "FR" in values and isinstance(values["FR"], pd.DataFrame) else "NA"
        
        print(f"{keys} : EN: {en_cols}, FR: {fr_cols}")

        # create a report df

In [36]:

def save_merged_dict_to_excel(merged_dict):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"Hyundai_Master_ACCY_Ready_To_Load_{timestamp}.xlsx"
    directory = r"..\ready_to_upload\master_files"
    file_path = os.path.join(directory, filename)

    os.makedirs(directory, exist_ok=True)

    with pd.ExcelWriter(file_path, engine='openpyxl') as writer:
        for model, lang_dict in merged_dict.items():
            for lang, df in lang_dict.items():
                sheet_name = f"{model}_{lang}"[:31]

                if isinstance(df, pd.DataFrame):
                    if not df.empty:
                        # Write normal sheet
                        df.to_excel(writer, sheet_name=sheet_name, index=False)
                    else:
                        # Write empty sheet
                        pd.DataFrame({"Message": ["No data available"]}).to_excel(writer, sheet_name=sheet_name, index=False)

                        # Apply orange tab color
                        ws = writer.book[sheet_name]
                        ws.sheet_properties.tabColor = "FFA500"  # Orange hex code

        # If no sheets were written at all, create a placeholder
        if not writer.sheets:
            pd.DataFrame({"Message": ["No data available"]}).to_excel(writer, sheet_name="Empty", index=False)
            ws = writer.book["Empty"]
            ws.sheet_properties.tabColor = "FFA500"  # Orange tab color

    return file_path

In [37]:

# check if each 
# Get a list of unique model numbers from both Hyundia_db and uniq accy_list dict 
# store them in vars named db_mdNumCount and file_mdNumCount
# Create column is_identical to check if they are identical  
# Create column is_equal_count to check if they are equal in length
# create column mdNUms_db
# create column mdNums_file

# Year/Model.countUniqModelNUmber() 
def data_check(year_model_trim_dict, hyundai_model_db_df): 
    data_check_report_df = pd.DataFrame(columns=["Year", "Model", "Trim", "Lang", "is_list_identical?", "db_mdNumCount", "file_mdNumCount", "mdNUms_db", "mdNums_file"])
    for (year, model, trim_name),value in year_model_trim_dict.items():
    
        # # get unique model numbers - files
        # FR_uniq_model_nums = value["FR"]["ModelNumber"].unique().tolist()
        # EN_uniq_model_nums = value["EN"]["ModelNumber"].unique().tolist()
        
        # get unique models numbers from 
        search_resp = fetch_model_numbers(year, model, trim_name)

        if search_resp["status"] == 400:
            db_mdNumCount = "Veh Not found in db"
            mdNums_from_db = []
        else:
            mdNums_from_db = search_resp["value"]
            db_mdNumCount = len(mdNums_from_db) 
        
        for lang, accy_list in value.items():
            
            if "ModelNumber" not in accy_list.columns:
                uniq_model_nums_list = "Error: File has no model number column"
                is_indentical_list = False
                count_mdNUms_from_accy_list = 0
                continue 
            else:
                uniq_model_nums_list = accy_list["ModelNumber"].unique().tolist()
                is_indentical_list = (mdNums_from_db == uniq_model_nums_list)
                count_mdNUms_from_accy_list = len(uniq_model_nums_list)

            new_record_df =  pd.DataFrame(
                [[year, 
                model, 
                trim_name, 
                lang,
                is_indentical_list, 
                db_mdNumCount, 
                count_mdNUms_from_accy_list, 
                mdNums_from_db, 
                uniq_model_nums_list]]
                , columns=["Year", "Model", "Trim", "Lang", "is_list_identical?", "db_mdNumCount", "file_mdNumCount", "mdNUms_db", "mdNums_file"])

            data_check_report_df = pd.concat([data_check_report_df, new_record_df], ignore_index=True)
            
    return data_check_report_df

In [38]:
def check_missing_model_numbers_report_model_db(missing_model_num_, hyundai_model_db_df):
    # missing model numbers report 
    missing_data_report_df = pd.DataFrame(columns=["Year", "Model", "Trim", "missingMd#?", "Comments"])

    for index, row in missing_model_num_.iterrows():
        
        # search the veh model in the model number db by year/model/ and trim
        
        search_result = hyundai_model_db_df[
            (1==1)
            & (hyundai_model_db_df["Year"] == row["Year"])
            & (hyundai_model_db_df["Model"] == row["Model"])
            & (hyundai_model_db_df["Trim"] == row["Trim"])
            ]

        if search_result.empty:
            mdNUmStatus = True
        else:
            mdNUmStatus = False

        new_row = pd.DataFrame(
                                [[row["Year"], row["Model"],row["Trim"], mdNUmStatus, "Missing model Number."]], 
                                columns=["Year", "Model", "Trim", "missingMd#?", "Comments"]
                            )  
        # concat dfs
        missing_data_report_df = pd.concat([missing_data_report_df, new_row], ignore_index=True)
    
    return missing_data_report_df

In [ ]:
# # Prepare the output filename with timestamp
# timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
# filename = "Hyundai_ACCY_load_report_{timestamp}.csv"
# directory = r"..\reports_log\Hyundai\data_load"
# output_path = os.path.join(directory, filename)

# data_load_report_check_df.to_csv(output_path, index=False)

In [40]:
# def create_tags_for_veh_trims(df):
#    # Decomposing trim to enable tagging
#    all_trim_names= df["Trim"].unique().tolist()
#    extracted_dict = {}
#    kwds_to_drop = ["w/t", "with"]
#    for item in all_trim_names:
#       if " " not in item:
#          parts = [item]

#       else:
#          parts = item.split()
      
#       extracted_dict[item]= {"tags" :parts} 

#    return extracted_dict
# # create_tags_for_veh_trims(dataset_summary)

In [41]:
# filtered_tags = filter_tags(tagy, (model_num_db_kwrd - master_df_kwdrs))

In [42]:

def find_missing_modelNums(df):
    # dataset_summary[dataset_summary["Trim"].str.contains("w/")]
    # counter = 0
    missing_model_numbers = pd.DataFrame(columns=["Year", "Model", "Trim"])

    for index, row in df.iterrows():
        Model_numbers_output = fetch_model_numbers(row.Year, row.Model, row.Trim)
        
        if 0 >= len(Model_numbers_output):
            # print(f"Year : {row.Year}, Model : {row.Model}, Trim : {row.Trim} -> No Model_numbers")
            missing_model_numbers.loc[len(missing_model_numbers)] = [row.Year, row.Model, row.Trim]
    return missing_model_numbers

In [43]:
hyundai_model_db_df = hyundai_model_load()   # Loading model number db

In [44]:
year_model_trim_dict, dataset_summary = data_extract_all(missing_model_num_)

In [45]:
# # year_model_trim_dict[(2026, 'Palisade', "Lux")]["EN"][year_model_trim_dict[(2026, 'Palisade', "Lux")]["EN"]["PartNumber"]=="DUF46ACC00CA"]

# year_model_trim_dict.keys()

In [46]:
# year_model_trim_dict[2024, 'Palisade', 'Pref']["EN"]

In [47]:


merged_files_dict = merge_lists_by_model_number(year_model_trim_dict)
save_merged_dict_to_excel(merged_dict= merged_files_dict)
# find_missing_modelNums(dataset_summary)
 
data_load_report_check_df = data_check(year_model_trim_dict, hyundai_model_db_df)
missing_data_report = check_missing_model_numbers_report_model_db(missing_model_num_, hyundai_model_db_df)

In [48]:
# merged_files_dict["Palisade"]["EN"]

In [49]:
# fetch_model_numbers(2026, "Tucson", "XRT")

In [ ]:

# missing_data_report[(~missing_data_report["Model"].str.contains("GV"))
#                     &(~missing_data_report["Model"].str.contains("G7"))
#                     &(~missing_data_report["Model"].str.contains("G8"))
#                     &(~missing_data_report["Model"].str.contains("G9"))
#                     &(~((missing_data_report["Model"]==("Tucson")) & (missing_data_report["Trim"].str.contains(r'xrt|Ult PHEV', case= False))))
#                     &(~((missing_data_report["Model"]==("Santa Fe")) & (missing_data_report["Trim"].str.contains(r'xrt|Lux ICE|Calli ICE', case= False))))
#                     &(~(missing_data_report["Model"]==("Santa Cruz")))
#                     # &(~((missing_data_report["Model"]=="Santa Cruz") & (missing_data_report["Trim"]=='Pref')))
#                     # & (~(missing_data_report["Model"]=="Santa Fe") & ~(missing_data_report["Trim"]=='Pref'))

#                     # & ~(missing_data_report["Model"].str.contains("Tucson") & missing_data_report["Trim"]==("N-Line"))
#                     # & ~(missing_data_report["Model"].str.contains("Tucson") & missing_data_report["Trim"].str.contains("Lux"))
#                     ]