In [5]:
import pandas as pd

from typing import List, Dict, Tuple

In [99]:
# read an excel and find all the sheet names
excel_file = pd.ExcelFile(r'..\database\raw_data\HYUNDAI NOV25.xlsx')

In [100]:
all_sheets_names = excel_file.sheet_names

In [ ]:
keyword_bridge = {
    "pref": "preferred",
    "preferred": "preferred",
    '2.5T': '2.5T', 
    '3.3T': '3.3T', 
    '3.5T' : '3.5T', 
    '5P':'5P', 
    '7P':'7P',
    'AWD':'AWD', 
    'Adv':'Adv', 
    'Advanced':'Advanced', 
    'Black':'Black',
    'Calli':'Calligraphy', 
    'Calligraphy':'Calligraphy', 
    'Coupe':'Coupe', 
    'Ed':'Edition', 
    'Ess': 'Essential', 
    'Essential':'Essential', 
    'HEV':'Hybrid', 
    'Hybrid':'Hybrid', 
    'ICE':'ICE', 
    'LR':'Long Range', 
    'Lux': 'Luxury', 
    'Luxury':'Luxury',
    'N':'N', 
    'N-Line':'N-Line', 
    'NHL':'NHL', 
    'PHEV':'Plug-In Hybrid',
    'Plug-In Hybrid':'Plug-In Hybrid', 
    'Performance':'Performance', 
    'Pkg':'Pkg', 
    'Plus':'Plus', 
    'Prestige':'Prestige', 
    'Long':'Long',
    'Range':'Range', 
    'Sport':'Sport', 
    'Tech':'Tech', 
    'Trend':'Trend', 
    'Ult':'Ult', 
    'Ultimate':'Ultimate', 
    'Urban':'Urban', 
    'XRT':'XRT', 
    'e-SC':'e-SC', 
    'eLSD':'eLSD',
    'IVT':'IVT',
    'EV': 'Electric',
    'Electric':'Electric',
    'GT':'GT',
    'Turbo':'Turbo',
    'Manual':'Manual',
    'Night':'Night',
    'DCT':'DCT',
    '2.0L':'2.0L', 
    'LE':'LE', 
    'FWD':'FWD',
    'Plug-In':'Plug-In'

}

In [216]:

import os
import json
print(os.path.exists(r'..\database\keywords_db\tokenized_key_words.json'))

with open(r'..\database\keywords_db\tokenized_key_words.json', 'r') as file:
    keyword_bridge = json.load(file)
    keyword_bridge = (lambda obj: {k.lower(): (v.lower() if isinstance(v, str) else v) for k, v in obj.items()})(keyword_bridge)

True

In [156]:
# model_name_exceptions = {
#     "EV": "EV",
#     "Electric":"EV"
# }

model_exceptions_for_naming_conventions = ["G80 EV","G70 EV", "Kona EV",  ]

In [ ]:
modelNum_identifier_key_words = ["HEV", "Hybrid", "EV", "Electric", "Plug-In Hybrid", "PHEV", "Essential"] 


un_necessary_key_words = ["Pref", "Urban", "Calli", "ICE", ]

In [224]:

import pandas as pd
from typing import List, Dict

def normalize(text: str) -> str:
    """Normalize text for case-insensitive matching."""
    return text.strip().lower()

def ensure_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Ensure required columns exist."""
    if 'Fixed_model' not in df.columns:
        df['Fixed_model'] = ''
    if 'Tags' not in df.columns:
        df['Tags'] = ''
    return df

def tokenize(text: str) -> List[str]:
    """Split text into tokens by spaces only, preserving hyphenated words."""
    clean_text = text.replace('(', '').replace(')', '').replace('/', ' ')
    tokens = clean_text.split()  # split only on spaces
    return [normalize(token) for token in tokens if token]

def to_camel_case_with_spaces(text: str) -> str:
    """Convert each word to CamelCase but keep spaces (e.g., 'kona ev' -> 'Kona EV')."""
    return ' '.join(word.capitalize() for word in text.split())

def process_row(model: str, trim: str, keyword_bridge: Dict[str, str], exceptions: List[str]) -> tuple[str, str]:
    normalized_bridge = {normalize(k): v for k, v in keyword_bridge.items()}
    normalized_exceptions = [normalize(e) for e in exceptions]
    tags_set = set()

    # Normalize model for exception check
    model_normalized = normalize(model)

    # Process model
    words_model = tokenize(model)
    if model_normalized in normalized_exceptions:
        fixed_model = model  # keep original if in exceptions
    else:
        fixed_words = []
        for word in words_model:
            if word in normalized_bridge:
                tags_set.add(normalized_bridge[word])
            else:
                fixed_words.append(word)
        fixed_model = ' '.join(fixed_words)

    # Convert fixed_model to CamelCase with spaces
    fixed_model = to_camel_case_with_spaces(fixed_model)

    # Process Trim
    words_trim = tokenize(trim)
    for word in words_trim:
        if word in normalized_bridge:
            tags_set.add(normalized_bridge[word])

    # Convert tags to CamelCase
    tags = ', '.join(sorted(to_camel_case_with_spaces(tag) for tag in tags_set))
    return fixed_model, tags

def apply_processing(df: pd.DataFrame, keyword_bridge: Dict[str, str], exceptions: List[str]) -> pd.DataFrame:
    if not {'Model', 'Trim'}.issubset(df.columns):
        raise KeyError("DataFrame must contain 'Model' and 'Trim' columns.")
    
    # Preprocessing: Standardize Electric -> EV in Model column
    df['Model'] = df['Model'].str.replace(r'\bElectric\b', 'EV', case=False, regex=True)

    df = ensure_columns(df)
    new_df = df.copy()
    for idx, row in new_df.iterrows():
        fixed_model, tags = process_row(row['Model'], row['Trim'], keyword_bridge, exceptions)
        new_df.at[idx, 'Fixed_model'] = fixed_model
        new_df.at[idx, 'Tags'] = tags
    
    df.columns = ['Year', 'ModelNumber', 'source_ModelName', 'Trim', 'Source_sheets', 'Model',
       'Tags']
    return new_df

In [218]:
# model_df_dict = pd.read_excel(r'..\database\raw_data\HYUNDAI NOV25.xlsx')


# Read all sheets into a dictionary
model_df_dict = pd.read_excel(r'..\database\raw_data\HYUNDAI NOV25.xlsx', sheet_name = None)

# Combine sheets and add sheet_name column
combined_df = pd.concat(
    [df.assign(sheet_name=sheet_name) for sheet_name, df in model_df_dict.items()],
    ignore_index=True
)

In [235]:
def clean_model_column(df):

    # 1. Remove tabs and trim whitespace
    df["Model"] = df["Model"].str.replace(r"\t", "", regex=True).str.strip()

    # 2. Convert text to Title Case
    df["Model"] = df["Model"].str.title()
    
    # Preprocessing: Standardize Electric -> EV in model column
    df['Model'] = df['Model'].str.replace(r'\bElectric\b', 'EV', case=False, regex=True)
    


    return df

In [244]:
def clean_df(df):
    df = df[["Model", "Description ", "Description", "Description 2", "sheet_name"]]
    df.columns = ['ModelNumber', 'Model1', 'Model2', 'Trim', 'Source_sheets']  # change column names

    df.loc[:, "Model1"] = df["Model1"].fillna(df["Model2"])
    # df.insert(1, 'Model', trim_col_data)

    df = df.drop(columns=['Model2'])

    
    # trim model number to remove /t
    ModelNumber = df["ModelNumber"].str.replace('\t', '', regex=True)
    trim = df["Trim"].replace('\t', '', regex=True)
    

    df["ModelNumber"] = ModelNumber
    df["Trim"] = trim
   
   # Preprocessing: Standardize Caligraphy -> Calligraphy in Trim column
    df['Trim'] = df['Trim'].str.replace(r'\bCaligraphy\b', 'Calligraphy', case=False, regex=True)
    

    # drop rows with null ModelNumbers
    df = df.dropna(subset=["ModelNumber"])

    # grab the year 
    # Extract 4-digit year from sheet_name and create a new column 'Year'
    year = df['Source_sheets'].str.extract(r'(\b\d{4}\b)')

    df.insert(0, 'Year', year)
    # Convert to integer (optional)
    df['Year'] = df['Year'].astype('Int64')  # Keeps NaN if no year found
    
    df.columns = ['Year', 'ModelNumber', 'Model', 'Trim', 'Source_sheets']
    
    df = df.drop_duplicates(subset=["ModelNumber", "Model", "Source_sheets"], keep="first")


    # # find duplicated model number and clean them-up
    
    
    df["ModelNumber"] = (
        df["ModelNumber"]
        .astype(str)                # Ensure all are strings
        .str.strip()                # Remove leading/trailing spaces
        .str.upper()                # Normalize case
        .str.replace(r"\s+", "", regex=True)  # Remove internal spaces
    )

    # 2. Remove hidden characters (non-printable)
    df["ModelNumber"] = df["ModelNumber"].str.replace(r"[^\x00-\x7F]+", "", regex=True)
    
    df = df.drop_duplicates(subset=["ModelNumber", "Year"], keep="first")
    

    df = clean_model_column(df)

    # special changes to stabdardize the data
    

    duplicates = df[df.duplicated(subset=["ModelNumber", "Year"], keep=False)]

    
    # # 4. Add count for clarity
    duplicates["DuplicateCount"] = duplicates.groupby(["ModelNumber", "Year"])["ModelNumber"].transform("count")

    # 5. Sort by most repeated
    duplicates = duplicates.sort_values(by="DuplicateCount", ascending=False)


    
    return df, duplicates

cleaned_models, duplicates = clean_df(combined_df)

In [246]:
cleaned_models[cleaned_models["Trim"].str.contains("Caligraphy")]

Empty DataFrame
Columns: [Year, ModelNumber, Model, Trim, Source_sheets]
Index: []

In [247]:
# 

processed_df = apply_processing(cleaned_models, keyword_bridge, model_exceptions_for_naming_conventions)

In [248]:
processed_df[(processed_df["Model"]=='Palisade') 
                    & (processed_df["Year"]==2024)
                    # & (hyundai_model_db_df["Tags"].str.contains("calligraphy"))
                    ]

,Year,ModelNumber,Model,Trim,Source_sheets,Fixed_model,Tags
260,2024,PACW8K3DPR00,Palisade,Preferred AWD,2024,Palisade,"Awd, Preferred"
261,2024,PACW8K3DUR00,Palisade,Urban AWD 8-Pass,2024,Palisade,"Awd, Urban"
262,2024,PACW7K3DUR91,Palisade,Urban AWD 7-Pass,2024,Palisade,"Awd, Urban"
263,2024,PACW7K3DULC7,Palisade,Ultimate Calligraphy AWD,2024,Palisade,"Awd, Calligraphy, Ultimate"
264,2024,PACW7K3DULCB,Palisade,Ultimate Calligraphy AWD (Beige Int.),2024,Palisade,"Awd, Calligraphy, Ultimate"
328,2024,PA1LAA38B200,Palisade,Preferred AWD,2024 (old),Palisade,"Awd, Preferred"
329,2024,PA1LAA38BY00,Palisade,Urban AWD 8-Pass,2024 (old),Palisade,"Awd, Urban"
330,2024,PA1LAA38BY91,Palisade,Urban AWD 7-Pass,2024 (old),Palisade,"Awd, Urban"
331,2024,PA1LAA38B477,Palisade,Ultimate Calligraphy AWD,2024 (old),Palisade,"Awd, Calligraphy, Ultimate"
332,2024,PA1LAA38B478,Palisade,Ultimate Calligraphy AWD (Beige Int.),2024 (old),Palisade,"Awd, Calligraphy, Ultimate"

In [230]:

def get_duplicates(df):
    # Show rows where ModelNumber, Model, and Source_sheets are all duplicated
    duplicates = cleaned_models[cleaned_models.duplicated(subset=["ModelNumber", "Model", "Source_sheets"], keep=False)]

    # Sort by frequency of these combined duplicates
    duplicates["DuplicateCount"] = duplicates.groupby(["ModelNumber", "Model", "Source_sheets"])["ModelNumber"].transform("count")
    duplicates = duplicates.sort_values(by="DuplicateCount", ascending=False)
    
    return duplicates
get_duplicates(processed_df)

Empty DataFrame
Columns: [Year, ModelNumber, source_ModelName, Trim, Source_sheets, Model, Tags, DuplicateCount]
Index: []

In [231]:
processed_df

,Year,ModelNumber,Model,Trim,Source_sheets,Fixed_model,Tags
0,2026,ELCS4V2BES00,Elantra,Essential,2026,Elantra,Essential
1,2026,ELCS4V2BPR00,Elantra,Preferred,2026,Elantra,Preferred
2,2026,ELCS4V2BPRTE,Elantra,with Tech Pkg,2026,Elantra,"Pkg, Tech"
3,2026,ELCS4V2BLU00,Elantra,Luxury,2026,Elantra,Luxury
4,2026,ELCS4V2BLUME,Elantra,Luxury (Two-Tone Interior),2026,Elantra,Luxury
...,...,...,...,...,...,...,...
689,2023,I51SEREME200,Ioniq 5,Preferred,CPO 2023,Ioniq 5,Preferred
690,2023,I51SEREME2AK,Ioniq 5,Preferred Long Range,CPO 2023,Ioniq 5,"Long, Preferred, Range"
691,2023,I51SEAEME2AK,Ioniq 5,Preferred AWD Long Range,CPO 2023,Ioniq 5,"Awd, Long, Preferred, Range"
692,2023,I51SEAEME2AZ,Ioniq 5,Preferred AWD Long Range with Luxury package,CPO 2023,Ioniq 5,"Awd, Long, Luxury, Preferred, Range"
693,2023,I51SEAEME2AV,Ioniq 5,Preferred AWD Long Range with Ultimate package,CPO 2023,Ioniq 5,"Awd, Long, Preferred, Range, Ultimate"

In [249]:
processed_df.to_csv(r'..\database\dbs\Hyundai_models_db.csv', index=False)

In [91]:
def search_vehicle_by_year_and_model(year, model):
    # Filter the DataFrame based on year and model
    filtered_df = cleaned_models[
        (cleaned_models['Year'] == year) & 
        (cleaned_models['Model'].str.contains(model, case=False, na=False))
    ]
    return filtered_df


def search_vehicle_by_model(model):
    # Filter the DataFrame based on model
    filtered_df = cleaned_models[ 
        (cleaned_models['Model'].str.contains(model, case=False, na=False))
    ]
    return filtered_df

def search_vehicle_by_model_and_trim_keyword(model, trim_search_key):
    # Filter the DataFrame based on model and trim key 
    filtered_df = cleaned_models[ 
        (cleaned_models['Model'].str.contains(model, case=False, na=False)) 
        & (cleaned_models['Trim'].str.contains(trim_search_key, case=False, na=False))
    ]
    return filtered_df

In [233]:
processed_df

,Year,ModelNumber,Model,Trim,Source_sheets,Fixed_model,Tags
0,2026,ELCS4V2BES00,Elantra,Essential,2026,Elantra,Essential
1,2026,ELCS4V2BPR00,Elantra,Preferred,2026,Elantra,Preferred
2,2026,ELCS4V2BPRTE,Elantra,with Tech Pkg,2026,Elantra,"Pkg, Tech"
3,2026,ELCS4V2BLU00,Elantra,Luxury,2026,Elantra,Luxury
4,2026,ELCS4V2BLUME,Elantra,Luxury (Two-Tone Interior),2026,Elantra,Luxury
...,...,...,...,...,...,...,...
689,2023,I51SEREME200,Ioniq 5,Preferred,CPO 2023,Ioniq 5,Preferred
690,2023,I51SEREME2AK,Ioniq 5,Preferred Long Range,CPO 2023,Ioniq 5,"Long, Preferred, Range"
691,2023,I51SEAEME2AK,Ioniq 5,Preferred AWD Long Range,CPO 2023,Ioniq 5,"Awd, Long, Preferred, Range"
692,2023,I51SEAEME2AZ,Ioniq 5,Preferred AWD Long Range with Luxury package,CPO 2023,Ioniq 5,"Awd, Long, Luxury, Preferred, Range"
693,2023,I51SEAEME2AV,Ioniq 5,Preferred AWD Long Range with Ultimate package,CPO 2023,Ioniq 5,"Awd, Long, Preferred, Range, Ultimate"

In [206]:
def search_model_y_m_t(Year, Model, Trim):
    return processed_df[
        (1==1)
        &(processed_df["Year"] == Year)
        &(processed_df["Model"] == Model)
        &(processed_df["Trim"].str.contains(Trim, case=False))
        ]

In [ ]:
search_model_y_m_t(2024,'Palisade', 'Calligraphy')

,Year,ModelNumber,Model,Trim,Source_sheets,Fixed_model,Tags
260,2024,PACW8K3DPR00,Palisade,Preferred AWD,2024,Palisade,"Awd, Preferred"
261,2024,PACW8K3DUR00,Palisade,Urban AWD 8-Pass,2024,Palisade,"Awd, Urban"
262,2024,PACW7K3DUR91,Palisade,Urban AWD 7-Pass,2024,Palisade,"Awd, Urban"
263,2024,PACW7K3DULC7,Palisade,Ultimate Caligraphy AWD,2024,Palisade,"Awd, Ultimate"
264,2024,PACW7K3DULCB,Palisade,Ultimate Caligraphy AWD (Beige Int.),2024,Palisade,"Awd, Ultimate"
328,2024,PA1LAA38B200,Palisade,Preferred AWD,2024 (old),Palisade,"Awd, Preferred"
329,2024,PA1LAA38BY00,Palisade,Urban AWD 8-Pass,2024 (old),Palisade,"Awd, Urban"
330,2024,PA1LAA38BY91,Palisade,Urban AWD 7-Pass,2024 (old),Palisade,"Awd, Urban"
331,2024,PA1LAA38B477,Palisade,Ultimate Caligraphy AWD,2024 (old),Palisade,"Awd, Ultimate"
332,2024,PA1LAA38B478,Palisade,Ultimate Caligraphy AWD (Beige Int.),2024 (old),Palisade,"Awd, Ultimate"