# VW Canada Accessories — Data Analysis

In [2]:
import pandas as pd

In [3]:


FILE = "2026_10_20_VW Canada Accessories Data EN.xlsx"

xls = pd.ExcelFile(FILE)
print(xls.sheet_names)

['Sheet1']

In [4]:
df = xls.parse(xls.sheet_names[0])
print(df.shape)
df.head()

(24397, 17)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,stockCode,make name,model,make&model,year range,status,productDescription,specialNote,applicationNotes,dealerNotes,mediaName,MSRP,cost,laborTime,vendor,categoryName,categoryParentName
1,000019819C,Volkswagen,Alltrack,000019819CAlltrack,2017-2019,Active,Seat Underlay with Backrest Cover - Black and ...,<p>Volkswagen Original seat covers not only lo...,"Keyword(s): sun, shade, sunshade, shield, refl...",NaN,Volkswagen Accessories - Canada,82,57.4,10,Volkswagen Zubehoer,Sun Protection,Comfort and Protection
2,000019819C,Volkswagen,Alltrack,000019819CAlltrack,2017-2019,Active,Seat Underlay with Backrest Cover - Black and ...,<p>Volkswagen Original seat covers not only lo...,"Keyword(s): sun, shade, sunshade, shield, refl...",NaN,Volkswagen Accessories - Canada,82,57.4,10,Volkswagen Zubehoer,Sun Protection,Comfort and Protection
3,000019819C,Volkswagen,Alltrack,000019819CAlltrack,2017-2019,Active,Seat Underlay with Backrest Cover - Black and ...,<p>Volkswagen Original seat covers not only lo...,"Keyword(s): sun, shade, sunshade, shield, refl...",NaN,Volkswagen Accessories - Canada,82,57.4,10,Volkswagen Zubehoer,Sun Protection,Comfort and Protection
4,000019819C,Volkswagen,Arteon,000019819CArteon,2019-2021,Active,Seat Underlay with Backrest Cover - Black and ...,<p>Volkswagen Original seat covers not only lo...,"Keyword(s): sun, shade, sunshade, shield, refl...",NaN,Volkswagen Accessories - Canada,82,57.4,10,Volkswagen Zubehoer,Sun Protection,Comfort and Protection

In [5]:
# Promote first row to header
df.columns = df.iloc[0]
df = df.iloc[1:].reset_index(drop=True)
df.columns.name = None
print(df.shape)
df.head()

(24396, 17)

,stockCode,make name,model,make&model,year range,status,productDescription,specialNote,applicationNotes,dealerNotes,mediaName,MSRP,cost,laborTime,vendor,categoryName,categoryParentName
0,000019819C,Volkswagen,Alltrack,000019819CAlltrack,2017-2019,Active,Seat Underlay with Backrest Cover - Black and ...,<p>Volkswagen Original seat covers not only lo...,"Keyword(s): sun, shade, sunshade, shield, refl...",NaN,Volkswagen Accessories - Canada,82,57.4,10,Volkswagen Zubehoer,Sun Protection,Comfort and Protection
1,000019819C,Volkswagen,Alltrack,000019819CAlltrack,2017-2019,Active,Seat Underlay with Backrest Cover - Black and ...,<p>Volkswagen Original seat covers not only lo...,"Keyword(s): sun, shade, sunshade, shield, refl...",NaN,Volkswagen Accessories - Canada,82,57.4,10,Volkswagen Zubehoer,Sun Protection,Comfort and Protection
2,000019819C,Volkswagen,Alltrack,000019819CAlltrack,2017-2019,Active,Seat Underlay with Backrest Cover - Black and ...,<p>Volkswagen Original seat covers not only lo...,"Keyword(s): sun, shade, sunshade, shield, refl...",NaN,Volkswagen Accessories - Canada,82,57.4,10,Volkswagen Zubehoer,Sun Protection,Comfort and Protection
3,000019819C,Volkswagen,Arteon,000019819CArteon,2019-2021,Active,Seat Underlay with Backrest Cover - Black and ...,<p>Volkswagen Original seat covers not only lo...,"Keyword(s): sun, shade, sunshade, shield, refl...",NaN,Volkswagen Accessories - Canada,82,57.4,10,Volkswagen Zubehoer,Sun Protection,Comfort and Protection
4,000019819C,Volkswagen,Arteon,000019819CArteon,2019-2021,Active,Seat Underlay with Backrest Cover - Black and ...,<p>Volkswagen Original seat covers not only lo...,"Keyword(s): sun, shade, sunshade, shield, refl...",NaN,Volkswagen Accessories - Canada,82,57.4,10,Volkswagen Zubehoer,Sun Protection,Comfort and Protection

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24396 entries, 0 to 24395
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stockCode           24396 non-null  object
 1   make name           24396 non-null  str
 2   model               24396 non-null  str
 3   make&model          24396 non-null  str
 4   year range          24396 non-null  str
 5   status              24396 non-null  str
 6   productDescription  24396 non-null  str
 7   specialNote         24127 non-null  str
 8   applicationNotes    22595 non-null  str
 9   dealerNotes         11152 non-null  str
 10  mediaName           24396 non-null  str
 11  MSRP                24396 non-null  object
 12  cost                24396 non-null  object
 13  laborTime           24396 non-null  object
 14  vendor              24260 non-null  str
 15  categoryName        24356 non-null  str
 16  categoryParentName  24356 non-null  str
dtypes: object(4), str(13)
memory usage: 3.2+ MB

In [7]:
df.columns

Index(['stockCode', 'make name', 'model', 'make&model', 'year range', 'status',
       'productDescription', 'specialNote', 'applicationNotes', 'dealerNotes',
       'mediaName', 'MSRP', 'cost', 'laborTime', 'vendor', 'categoryName',
       'categoryParentName'],
      dtype='object')

In [8]:
essential_columns = ['stockCode', 'model', 'make&model', 'year range', 'status', 'productDescription', 'dealerNotes','MSRP', 'cost', 'laborTime']


# new df that contains only the essential columns
df_essential = df[essential_columns]

In [9]:
df_essential.columns

Index(['stockCode', 'model', 'make&model', 'year range', 'status',
       'productDescription', 'dealerNotes', 'MSRP', 'cost', 'laborTime'],
      dtype='object')

In [10]:

df_essential.info()

<class 'pandas.DataFrame'>
RangeIndex: 24396 entries, 0 to 24395
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stockCode           24396 non-null  object
 1   model               24396 non-null  str
 2   make&model          24396 non-null  str
 3   year range          24396 non-null  str
 4   status              24396 non-null  str
 5   productDescription  24396 non-null  str
 6   dealerNotes         11152 non-null  str
 7   MSRP                24396 non-null  object
 8   cost                24396 non-null  object
 9   laborTime           24396 non-null  object
dtypes: object(4), str(6)
memory usage: 1.9+ MB

In [11]:
# create a dictionary to map columns to new data types, and new names that they should take. 
column_mapping = {
    
    'stockCode': ('part_number', str),
    'model': ('model_name', str),
    'make&model': ('make_model', str),
    'year range': ('year_range', str),
    'status': ('status', str),
    'productDescription': ('product_description', str),
    'dealerNotes': ('comments', str),
    'MSRP': ('msrp', float),
    'cost': ('cost', float),
    'laborTime': ('labor_time', float)
}

# create a function to rename the columns and change their data types
def transform_essential_data(df, column_mapping=column_mapping):
    df = df.rename(columns={col: new_name for col, (new_name, _) in column_mapping.items()})
    df = df.astype({new_name: dtype for new_name, dtype in column_mapping.values()})
    return df

df_essential = transform_essential_data(df_essential)

In [12]:
# filter data to only include rows where the status is 'Active'
df_essential = df_essential[df_essential['status'] == 'Active']

# df_essential = df_essential.drop(columns=['status'])

In [13]:

# drop columns that are not needed for analysis

drop_columns = ["status", "make_model"]
df_essential.drop(columns=drop_columns, inplace=True)

In [14]:
df_essential.head()

,part_number,model_name,year_range,product_description,comments,msrp,cost,labor_time
0,000019819C,Alltrack,2017-2019,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0
1,000019819C,Alltrack,2017-2019,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0
2,000019819C,Alltrack,2017-2019,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0
3,000019819C,Arteon,2019-2021,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0
4,000019819C,Arteon,2019-2021,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0

In [15]:
import numpy as np

# create a function to clean the data: trim leading/trailing spaces and replace empty strings with NaN
def clean_data(df):
    df = df.map(lambda x: x.strip() if isinstance(x, str) else x)
    df = df.replace("", np.nan)
    return df

df_essential = clean_data(df_essential)

In [16]:
df_essential.head()

,part_number,model_name,year_range,product_description,comments,msrp,cost,labor_time
0,000019819C,Alltrack,2017-2019,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0
1,000019819C,Alltrack,2017-2019,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0
2,000019819C,Alltrack,2017-2019,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0
3,000019819C,Arteon,2019-2021,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0
4,000019819C,Arteon,2019-2021,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0

In [17]:

df_essential.info()

<class 'pandas.DataFrame'>
Index: 20399 entries, 0 to 24395
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   part_number          20399 non-null  str
 1   model_name           20399 non-null  str
 2   year_range           20399 non-null  str
 3   product_description  20399 non-null  str
 4   comments             8183 non-null   str
 5   msrp                 20399 non-null  float64
 6   cost                 20399 non-null  float64
 7   labor_time           20399 non-null  float64
dtypes: float64(3), str(5)
memory usage: 1.4 MB

In [18]:
# Analysis of the model_name column: how many unique values we have
print(f"Unique model names: {df_essential['model_name'].nunique()}")
print(f"Missing (NaN) values: {df_essential['model_name'].isna().sum()}")

# list each unique model with its row count
df_essential['model_name'].value_counts(dropna=False)

Unique model names: 31
Missing (NaN) values: 0

model_name
Jetta                 2130
GTI                   1808
Jetta GLI             1560
Tiguan                1529
Golf                  1426
Passat                1232
Atlas                 1208
Beetle                 914
Golf R                 878
Atlas Cross Sport      738
Passat Wagon           715
Touareg                646
SportWagen             607
Beetle Convertible     601
ID.4                   565
Taos                   439
CC                     415
Eos                    396
e-Golf                 337
Arteon                 304
EuroVan                246
Cabrio                 227
Jetta Wagon            223
Rabbit                 188
Routan                 185
City Golf              178
Alltrack               177
Jetta Hybrid           172
City Jetta             164
ID. Buzz               116
R32                     75
Name: count, dtype: int64

In [19]:
# For each year range, count the records of each model present in it
year_model_counts = (
    df_essential
    .groupby(['year_range', 'model_name'], dropna=False)
    .size()
    .reset_index(name='count')
    .sort_values(['year_range', 'count'], ascending=[True, False])
)

print(f"Unique year ranges: {year_model_counts['year_range'].nunique()}")
year_model_counts

Unique year ranges: 177

    year_range         model_name  count
0    1990-2010       Passat Wagon    560
1    1990-2018              Jetta     29
4    1990-2020             Passat     30
2    1990-2020               Golf     28
3    1990-2020          Jetta GLI     21
..         ...                ...    ...
323  2025-2026           ID. Buzz      2
326  2026-2026                GTI      2
325  2026-2026  Atlas Cross Sport      1
327  2026-2026             Golf R      1
328  2026-2026              Jetta      1

[329 rows x 3 columns]

In [20]:
# # filter the df to rows whose year_range end year (after the "-") is min_end_year or higher
# def filter_by_min_end_year(df, min_end_year=2020):
#     # end year = the part after the "-" (or the whole value if there is no "-")
#     end_year = pd.to_numeric(df['year_range'].str.split('-').str[-1].str.strip(), errors='coerce')
#     return df[end_year >= min_end_year]


# # count the records of each model present in each year range, for year ranges ending in min_end_year or later
# def count_models_from_end_year(df, min_end_year=2020):
#     filtered = filter_by_min_end_year(df, min_end_year)

#     return (
#         filtered
#         .groupby(['year_range', 'model_name'], dropna=False)
#         .size()
#         .reset_index(name='count')
#         .sort_values(['year_range', 'count'], ascending=[True, False])
#     )

# df_recent = filter_by_min_end_year(df_essential, min_end_year=2020)
# print(f"Rows with end year 2020 or later: {len(df_recent)}")

# recent_model_counts = count_models_from_end_year(df_essential, min_end_year=2020)
# print(f"Year ranges ending in 2020 or later: {recent_model_counts['year_range'].nunique()}")
# recent_model_counts

In [21]:
# split year_range (e.g. "2019-2021") into min_year and max_year columns
def split_year_range(df):
    df = df.copy()
    years = df['year_range'].str.split('-', n=1, expand=True)

    df['min_year'] = pd.to_numeric(years[0].str.strip(), errors='coerce').astype('Int64')
    # if there is no "-", max_year is the same as min_year
    df['max_year'] = pd.to_numeric(years[1].str.strip(), errors='coerce').astype('Int64').fillna(df['min_year'])
    return df

df_essential = split_year_range(df_essential)

In [22]:
filtered_recent_df = df_essential[df_essential['max_year'] >= 2020]

In [23]:

filtered_recent_df.head()

,part_number,model_name,year_range,product_description,comments,msrp,cost,labor_time,min_year,max_year
3,000019819C,Arteon,2019-2021,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0,2019,2021
4,000019819C,Arteon,2019-2021,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0,2019,2021
5,000019819C,Arteon,2019-2021,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0,2019,2021
6,000019819C,Atlas Cross Sport,2020-2026,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0,2020,2026
7,000019819C,Atlas Cross Sport,2020-2026,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0,2020,2026

In [24]:
# remove duplicated records, comparing the values in all the columns

def remove_duplicates(df):
    before = len(df)
    df = df.drop_duplicates(keep='first').reset_index(drop=True)
    print(f"Removed {before - len(df)} duplicate rows ({before} -> {len(df)})")
    return df

filtered_recent_df = remove_duplicates(filtered_recent_df)

Removed 11694 duplicate rows (13051 -> 1357)

In [25]:

filtered_recent_df.head()

,part_number,model_name,year_range,product_description,comments,msrp,cost,labor_time,min_year,max_year
0,000019819C,Arteon,2019-2021,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0,2019,2021
1,000019819C,Atlas Cross Sport,2020-2026,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0,2020,2026
2,000019819C,e-Golf,2015-2020,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0,2015,2020
3,000019819C,Golf,1990-2021,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0,1990,2021
4,000019819C,Golf R,2012-2026,Seat Underlay with Backrest Cover - Black and ...,NaN,82.0,57.4,10.0,2012,2026

In [26]:
# Df contains only the records with max_year >= 2020, and no duplicates

filtered_recent_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1357 entries, 0 to 1356
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   part_number          1357 non-null   str
 1   model_name           1357 non-null   str
 2   year_range           1357 non-null   str
 3   product_description  1357 non-null   str
 4   comments             654 non-null    str
 5   msrp                 1357 non-null   float64
 6   cost                 1357 non-null   float64
 7   labor_time           1357 non-null   float64
 8   min_year             1357 non-null   Int64
 9   max_year             1357 non-null   Int64
dtypes: Int64(2), float64(3), str(5)
memory usage: 108.8 KB

In [27]:
#  unique model names and their counts in the filtered df

filtered_recent_df["model_name"].value_counts(dropna=False)

model_name
Atlas                154
Tiguan               146
ID. Buzz             115
Atlas Cross Sport    114
GTI                  109
Jetta                 98
ID.4                  95
Jetta GLI             90
Taos                  90
Golf R                87
Golf                  82
Arteon                77
e-Golf                50
Passat                50
Name: count, dtype: int64

In [28]:

filtered_recent_df.columns

Index(['part_number', 'model_name', 'year_range', 'product_description',
       'comments', 'msrp', 'cost', 'labor_time', 'min_year', 'max_year'],
      dtype='str')

In [29]:
# business rules for the data quality check (source column names are mapped to the renamed ones via column_mapping)
data_rules = {
    'greater_than':         [('MSRP', 'cost')],                # left value must be > right value
    'greater_or_equal':     [('max_year', 'min_year')],        # left value must be >= right value
    'not_null':             ['stockCode', 'model', 'productDescription', 'MSRP', 'cost', 'laborTime'],
    'numeric_non_zero':     ['msrp', 'cost', 'min_year', 'max_year'],
    'numeric_non_negative': ['labor_time'],                    # zero or more
}

def data_quality_check(df, data_rules, column_mapping=column_mapping):
    rename = {src: new for src, (new, _) in column_mapping.items()}
    col = lambda c: rename.get(c, c)

    results = []      # one row per rule check
    failed_rows = {}  # rule description -> rows that broke it

    def record(rule, columns, mask=None, note=''):
        n_failed = int(mask.sum()) if mask is not None else None
        status = 'MISSING COLUMN' if mask is None else ('PASS' if n_failed == 0 else 'FAIL')
        results.append({'rule': rule, 'columns': columns, 'status': status, 'failed_rows': n_failed, 'note': note})
        if mask is not None and n_failed:
            failed_rows[f"{rule}: {columns}"] = df[mask]

    def missing(*cols):
        return [c for c in cols if c not in df.columns]

    for rule in ('greater_than', 'greater_or_equal'):
        for left, right in data_rules.get(rule, []):
            l, r = col(left), col(right)
            label = f"{l} {'>' if rule == 'greater_than' else '>='} {r}"
            if missing(l, r):
                record(rule, label, note=f"not in df: {missing(l, r)}")
                continue
            ok = df[l] > df[r] if rule == 'greater_than' else df[l] >= df[r]
            record(rule, label, ~ok.fillna(False).astype(bool))

    for c in data_rules.get('not_null', []):
        if missing(col(c)):
            record('not_null', col(c), note=f"'{c}' not in df")
            continue
        record('not_null', col(c), df[col(c)].isna())

    # numeric rules: a value fails if it is not a number, or if it breaks the condition
    numeric_fails = {
        'numeric_non_zero':     lambda v: v == 0,
        'numeric_non_negative': lambda v: v < 0,
    }
    for rule, fails in numeric_fails.items():
        for c in data_rules.get(rule, []):
            if missing(col(c)):
                record(rule, col(c), note=f"'{c}' not in df")
                continue
            values = pd.to_numeric(df[col(c)], errors='coerce')
            record(rule, col(c), (values.isna() | fails(values)).astype(bool))

    report = pd.DataFrame(results)
    broken = report['status'].ne('PASS').sum()
    print(f"Data quality check: {len(report)} checks, {broken} with issues")
    return report, failed_rows

In [30]:
dq_report, dq_failed_rows = data_quality_check(filtered_recent_df, data_rules)
dq_report

Data quality check: 13 checks, 0 with issues

                    rule               columns status  failed_rows note
0           greater_than           msrp > cost   PASS            0
1       greater_or_equal  max_year >= min_year   PASS            0
2               not_null           part_number   PASS            0
3               not_null            model_name   PASS            0
4               not_null   product_description   PASS            0
5               not_null                  msrp   PASS            0
6               not_null                  cost   PASS            0
7               not_null            labor_time   PASS            0
8       numeric_non_zero                  msrp   PASS            0
9       numeric_non_zero                  cost   PASS            0
10      numeric_non_zero              min_year   PASS            0
11      numeric_non_zero              max_year   PASS            0
12  numeric_non_negative            labor_time   PASS            0

In [31]:
# dict: model_name -> df with one record per applicable year (min_year to max_year, inclusive)

output_columns = ['part_number', 'model_name', 'product_description', 'comments',
                  'msrp', 'cost', 'labor_time', 'min_year', 'max_year', 'applicable_year']

def build_model_year_dict(df):
    df = df.copy()
    # list of every year in the range, then one row per year
    df['applicable_year'] = [list(range(int(lo), int(hi) + 1)) for lo, hi in zip(df['min_year'], df['max_year'])]
    df = df.explode('applicable_year')
    df['applicable_year'] = df['applicable_year'].astype(int)

    return {
        model: group[output_columns].sort_values(['part_number', 'applicable_year']).reset_index(drop=True)
        for model, group in df.groupby('model_name')
    }

In [32]:

model_year_dict = build_model_year_dict(filtered_recent_df)

for model, model_df in model_year_dict.items():
    print(f"{model}: {len(model_df)} records")

Arteon: 307 records
Atlas: 1200 records
Atlas Cross Sport: 738 records
GTI: 1712 records
Golf: 1397 records
Golf R: 912 records
ID. Buzz: 116 records
ID.4: 567 records
Jetta: 1842 records
Jetta GLI: 1706 records
Passat: 1052 records
Taos: 439 records
Tiguan: 1409 records
e-Golf: 265 records

In [33]:

model_year_dict["Arteon"]

,part_number,model_name,product_description,comments,msrp,cost,labor_time,min_year,max_year,applicable_year
0,000019819C,Arteon,Seat Underlay with Backrest Cover - Black and ...,NaN,82.00,57.4,10.0,2019,2021,2019
1,000019819C,Arteon,Seat Underlay with Backrest Cover - Black and ...,NaN,82.00,57.4,10.0,2019,2021,2020
2,000019819C,Arteon,Seat Underlay with Backrest Cover - Black and ...,NaN,82.00,57.4,10.0,2019,2021,2021
3,000051446CA,Arteon,Illuminated Media Cable - USB-C® to Apple® Lig...,Always install the product according to the ma...,57.40,39.2,0.0,2021,2023,2021
4,000051446CA,Arteon,Illuminated Media Cable - USB-C® to Apple® Lig...,Always install the product according to the ma...,57.40,39.2,0.0,2021,2023,2022
...,...,...,...,...,...,...,...,...,...,...
302,ZVW355001,Arteon,License plate frame - Slim - Polished,"|Before installing your license plate frame, c...",42.05,28.7,0.0,2019,2023,2019
303,ZVW355001,Arteon,License plate frame - Slim - Polished,"|Before installing your license plate frame, c...",42.05,28.7,0.0,2019,2023,2020
304,ZVW355001,Arteon,License plate frame - Slim - Polished,"|Before installing your license plate frame, c...",42.05,28.7,0.0,2019,2023,2021
305,ZVW355001,Arteon,License plate frame - Slim - Polished,"|Before installing your license plate frame, c...",42.05,28.7,0.0,2019,2023,2022
306,ZVW355001,Arteon,License plate frame - Slim - Polished,"|Before installing your license plate frame, c...",42.05,28.7,0.0,2019,2023,2023

In [35]:
# load the VW model data exported from accy_v2/model_lookup/veh_model_service.ipynb
VW_MODELS_FILE = "vw_models_data.csv"

# keep ModelNumber/Package/Style_ID as text so codes are not converted to numbers
vw_models_df = pd.read_csv(VW_MODELS_FILE, dtype={'ModelNumber': str, 'Package': str, 'Style_ID': str})
print(vw_models_df.shape)

(323, 11)

In [ ]:
vw_models_df.head()

,Description,Drivetrain,Manufacturer,ModelName,ModelNumber,ModelYear,Package,PassDoors,Style_ID,TrimName,engine_type
0,Jetta Highline Auto,NaN,VOLKSWAGEN,NaN,BU33MS,2019,NaN,NaN,NaN,NaN,NaN
1,Jetta Comfortline Manual,NaN,VOLKSWAGEN,NaN,BU32M2,2019,NaN,NaN,NaN,NaN,NaN
2,Jetta Comfortline Auto,NaN,VOLKSWAGEN,NaN,BU32MS,2019,NaN,NaN,NaN,NaN,NaN
3,Jetta Highline Manual,NaN,VOLKSWAGEN,NaN,BU33M2,2019,NaN,NaN,NaN,NaN,NaN
4,Jetta Execline Manual,NaN,VOLKSWAGEN,NaN,BU34M2,2019,NaN,NaN,NaN,NaN,NaN

In [38]:
# drop empty columns and rows with all NaN values
vw_models_df.dropna(axis=1, how='all', inplace=True)
vw_models_df.dropna(axis=0, how='all', inplace=True)

In [40]:

vw_models_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 323 entries, 0 to 322
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Description   323 non-null    str
 1   Manufacturer  323 non-null    str
 2   ModelNumber   323 non-null    str
 3   ModelYear     323 non-null    int64
dtypes: int64(1), str(3)
memory usage: 10.2 KB

In [41]:
vw_models_df.describe(include='all')

           Description Manufacturer ModelNumber    ModelYear
count              323          323         323   323.000000
unique             142            1         159          NaN
top     Taos Trendline   VOLKSWAGEN      CMC2NR          NaN
freq                 8          323           4          NaN
mean               NaN          NaN         NaN  2022.386997
std                NaN          NaN         NaN     2.398644
min                NaN          NaN         NaN  2019.000000
25%                NaN          NaN         NaN  2020.000000
50%                NaN          NaN         NaN  2022.000000
75%                NaN          NaN         NaN  2024.000000
max                NaN          NaN         NaN  2027.000000